INVALID_TAGS = [
    "none",
    "unknown",
    "rason",
    "ransom",
    "misc",
    "various",
    "undefined",
    "untitled",
    "demo",
    "sample",
    "test",
    "mix",
    "compilation",
    "album",
    "recordings",
    "track",
    "music",
    "expiremental",
    "diy record label",
    "tantron",
    "andinostep",
    "foknbois",
    "mariusz szypura",
    "portland",
    "other stuff",
    "philipp nespital",
    "cometogether",
    "dj tramlife",
    "mlvltd",
    "deffa heffa",
    "wizard sleaze",
    "goose bumps",
    "sabaton",
    "metallica",
    "iron maiden",
    "led zeppelin",
    "pink floyd",
    "the beatles",
    "queen",
    "ac/dc",
    "nirvana",
    "carcass",
    "oliver mtukudzi",
    "tolkien",
    "comets on fire",
    "romania",
    "black uhuru",
    "halloween ep",
    "concept album",
    "Reading",
    "cecil mcbee",
    "King Gizzard & The Lizard Wizard",
    "µ-Ziq",
    "la quiete",
    "good for nothing",
    "140",
    "compilation",
    "tolkien",
    "music",
    "160bpm",
    "dead-man's-flats",
    "c4cdiguk080",
    "carcass",
    "the-number-12-looks-like-you",
    "303",
    "2025",
    "2024",
    "dx7",
    "metallica",
    "dr.-dooom",
    "fm",
    "140-bpm",
    "exh012",
    "mlvltd",
    "ue2",
    "85bpm",
    "170bpm",
    "daniel[i]" "a.r.t.less",
    "4-track",
    "dr.-octagon",
    "em",
    "tantron",
    "j.-cash",
    "w",
    "t",
    "b",
    "tb303",
    "140bpm",
    "volume-2",
    "perc.-perc-trax",
    "cincinnati" "xerox-fax-machine's-superheroes" "dda\vaiii",
    "splinter-(ua)",
    "2017",
    "2018",
    "2019",
    "2020",
    "2021",
    "2022",
    "lgbtq+",
    "2005",
    "rason",
    "roland-r8",
    "splinter-(ua)",
    "dc",
    "cause4concern",
    "c4c-recordings",
    "c4c-limited",
    "c4c",
    "quadrant-&-iris",
    "cause4concern-recordings",
    "tv",
    "tennessee",
    "max4live",
    "uk.",
    "year0001",
    "@kendrick",
    "@drake",
    "f*clr-records",
    "boss-rc-500",
    "c64",
    "parker&thenumberman",
    "cyberpunk-2077",
    "arp-2600",
    "96khz",
    "sly-&-robbie",
    "nj",
    "prophet-12",
    "nonlinear-labs-c15",
    "2-piece-band",
    "cleveland",
    "singer-songwriter.",
    "kool-&-the-gang",
    "t++",
    "d",
    "manila",
    "cometogether",
    "tx",
    "milwaukee",
    "tuba",
    "compilation",
    "thomas morgan",
    "bill frisell",
    "jakob bro",
    "james farber",
    "wadada leo smith",
    "marcus gilmore",
    "avatar studios",
    "ben street",
    "bill frisell",
    "jakob bro",
    "james farber",
    "jørgen leth",
    "lee konitz",
    "paul motian",
    "Bellingham",
    "between the buried and me",
    "pink floyd",
    "dream theatre",
    "eclectic",
    "atmospheric",
    "cinematic",
    "36",
    "field recordings",
    "quiet details",
    "live album",
    "live show",
    "Bend",
    "arp",
    "arpeggiator",
    "arp2600",
    "b3 organ",
    "creative commons",
    "percussion",
    "reverb",
    "riser",
    "synth",
    "varied",
    "United States",
    "pipe organ",
    "erased tapes",
    "gondwana records",
    "max richter",
    "nils frahm",
    "philip glass",
    "jazz vocal jazz",
    "cheap records vienna",
    "140",
    "heavy",
    "heavy shit",
    "edits",
    "refixed",
    "Israel",
    "baile",
    "steve albini",
    "St. Louis",
    "jeff tweedy",
    "tiger moth tales",
    "genesis",
    "magenta",
    "big big train",
    "pete jones",
    "comets on fire",
    "drunk horse",
    "comets on fire",
    "feral ohms",
    "zig zags",
    "howlin rain",
    "primitive",
    "outcast",
    "mix",
    "Dead Man'S Flats",
    "antifascista",
]

GEO_TAGS = [
    "Brooklyn",
    "Stockholm",
    "Verona",
    "Milan",
    "Paris",
    "Argentina",
    "swiss",
    "Lausanne",
    "Oakland",
    "Munich",
    "Dublin",
    "Birmingham",
    "Amsterdam",
    "australian",
    "Helsinki",
    "Austin",
    "austin",
    "Hamburg",
    "Los Angeles",
    "Bristol",
    "berlin",
    "bristol",
    "Japan",
    "colorado",
    "Colombia",
    "Brazil",
    "Colorado",
    "California",
    "Seattle",
    "Monterrey",
    "United Kingdom",
    "Vienna",
    "Victoria",
    "Warsaw",
    "Helsinki",
    "Stockholm",
    "Portland",
    "Toronto",
    "London",
    "Melbourne",
    "Montreal",
    "Budapest",
    "Hungary",
    "new york city",
    "Chicago",
    "United Kingdom",
    "Zürich",
    "Sweden",
    "Copenhagen",
    "Lancashire",
    "berlin",
    "london",
    "Chicago",
    "Los Angeles",
    "Phoenix",
    "St. Louis",
    "Rome",
    "denmark",
    "sweden",
    "norway",
    "finland",
    "iceland",
    "austria",
    "dc",
    "kyoto",
    "us",
    "ny",
    "beijing",
    "santiago",
    "baltimore",
    "wales",
    "hungary",
    "alabama",
    "moscow",
    "seoul",
    "wales",
    "finland" "st.-louis",
    "instanbul",
    "London",
    "london",
    "new york",
    "tokyo",
    "los angeles",
    "paris",
    "berlin",
    "rome",
    "madrid",
    "barcelona",
    "santiago",
    "buenos aires",
    "são paulo",
    "rio de janeiro",
    "melbourne",
    "sydney",
    "seoul",
    "beijing",
    "toronto",
    "montreal",
    "chicago",
    "vancouver",
    "mexico city",
    "bogotá",
    "lisbon",
    "amsterdam",
    "osaka",
    "kyoto",
    "warsaw",
    "moscow",
    "cape town",
    "boston",
    "manila",
    "jakarta",
    "istanbul",
    "athens",
    "Maryland",
    "california",
    "texas",
    "florida",
    "india",
    "brazil",
    "canada",
    "Peterborough",
    "hungary",
    "czech republic",
    "slovakia",
    "oakland",
    "Milan",
    "america",
    "europe",
    "asia",
    "africa",
    "australia",
    "usa",
    "uk",
    "philadelphia",
    "philadephia",
    "United States",
    "Deutschland",
    "España",
    "Italia",
    "Brasil",
    "Россия",
    "中国",
    "日本",
    "한국",
    "भारत",
    "ελλάδα",
    "turkiye",
    "colorado",
    "United Kingdom",
    "new zealand",
    "nz",
    "scotland",
    "wales",
    "northern ireland",
    "nyc",
    "Minneapolis",
    "houston",
    "atlanta",
    "detroit",
    "seattle",
    "denver",
    "Austin",
    "orlando",
    "cleveland",
    "pittsburgh",
    "cincinnati",
    "indianapolis",
    "milwaukee",
    "baltimore",
    "richmond",
    "virginia",
    "kentucky",
    "tennessee",
    "nashville",
    "memphis",
    "louisville",
    "alabama",
    "mississippi",
    "arkansas",
    "oklahoma",
    "new orleans",
    "louisiana",
    "Manchester",
    "United Kingdom",
    "london",
    "berlin",
    "melbourne",
    "paris",
    "chicago",
    "tokyo",
    "rome",
    "boston",
    "sydney",
    "amsterdam",
    "barcelona",
    "madrid",
    "vancouver",
    "chicago",
    "portland",
    "montreal",
    "toronto",
    "australia",
    "denver",
    "pittsburgh",
    "vancouver",
    "seattle",
    "boston",
    "uk",
    "california",
    "canada",
    "nashville",
    "atlanta",
    "sidney",
    "oakland",
    "brazil",
    "houston",
    "indianapolis",
    "texas",
    "colorado",
    "louisville",
    "richmond",
    "athens",
    "romania",
    "barcelona",
    "sabaton",
    "memphis",
    "rome",
    "usa",
    "madrid",
    "lisbon",
    "tokyo",
    "virginia",
    "philadelphia",
    "america",
    "africa",
    "scotland",
    "india",
    "warsaw",
    "florida",
    "istanbul",
    "nyc",
    "seoul",
    "moscow",
    "alabama",
    "hungary",
    "wales",
    "baltimore",
    "slovakia",
    "santiago",
    "beijing",
    "kyoto",
    "cincinnati",
    "us",
    "ny",
    "washington,-d.c.",
    "dc",
    "tennessee",
    "nj",
    "cleveland",
    "manila",
    "tx",  # abreviatura de Texas
    "milwaukee",
    "washington,-d.c.",
    "dc",
    "los-angeles",
    "united-states",
    "united-kingdom",
    "los-angeles",
    "united-states",
    "germany",
]
