# -*- coding: utf-8 -*-
"""
Diccionario maestro de equivalencias de tags musicales.
Su objetivo es unificar variantes tipográficas, lingüísticas y ortográficas
para lograr una taxonomía coherente en la visualización y el modelado.
"""

import unidecode

TAG_EQUIVALENCES = {
    #
    "horrorcore;-rap;-hip-hop,": "horrorcore",
    "drum-'n-bass": "drum and bass",
    "pos-punk": "post punk",
    "proto.house": "protohouse",
    "y2kaesthetic": "y2k",
    "postpunk": "post punk",
    "synthwave-&-darksynth": "synthwave",
    "post-punk": "post punk",
    "post-hardcore": "post hardcore",
    "posthardcore": "post hardcore",
    "mathrock": "math rock",
    "prog-rock": "progressive rock",
    "prog": "progressive rock",
    "psychedelic": "psychedelic rock",
    "psychedelia": "psychedelic rock",
    "space-rock": "space rock",
    "noise-rock": "noise rock",
    "classic-90s-house-music-vibes": "90s house",
    "90s-hip-hop-beats": "90s hip-hop/rap",
    "oi!": "oi! punk",
    "16bit": "16bit",
    "trip.hop": "trip hop",
    "y202": "y2k",
    "16-bit": "16bit",
    "oii": "oi! punk",
    "oi": "oi! punk",
    "#indie": "indie rock",
    "oi-punk": "oi! punk",
    "1970s-vibes": "70s vibes",
    "1980's-punk": "80s punk",
    "garage rock": "garage rock",
    "garage-rock": "garage rock",
    "garagepunk": "garage punk",
    "garage-punk": "garage punk",
    "surf-rock": "surf rock",
    "blues-rock": "blues rock",
    "indierock": "indie rock",
    "#indie-rock": "indie rock",
    "indie-rock": "indie rock",
    "indie": "indie rock",
    "indiepop": "indie pop",
    "indie-pop": "indie pop",
    "alt-rock": "alternative rock",
    "alternative": "alternative rock",
    "alternative-rock": "alternative rock",
    "#blues": "blues",
    "90s": "90s style",
    "80s": "80s style",
    "doom.-metal": "doom metal",
    #
    "synthpop": "synth pop",
    "synth-pop": "synth pop",
    "electropop": "electro pop",
    "dreampop": "dream pop",
    "dream-pop": "dream pop",
    "chillwave": "chillwave",
    "chill": "chillwave",
    "vapor-wave": "vaporwave",
    "lofi": "lofi",
    "lo-fi": "lofi",
    "lo-fi-beats": "lofi beats",
    "trip-hop": "trip hop",
    "hiphop": "hip-hop/rap",
    "late night lo-fi": "late night lofi",
    "hip-hop": "hip-hop/rap",
    "hip hop": "hip-hop/rap",
    "rap & hip-hop": "hip-hop/rap",
    "rap & hip hop": "hip-hop/rap",
    "rap & hiphop": "hip-hop/rap",
    "rap": "hip-hop/rap",
    "sludge": "sludge metal",
    "electronic": "electronic",
    "electronica": "electronic",
    "edm": "edm",
    "electro-house": "electro house",
    "deep-house": "deep house",
    "progressive-house": "progressive house",
    "hardstyle": "hardstyle",
    "techno": "techno",
    "acid-techno": "acid techno",
    "drum-n-bass": "drum and bass",
    "drum-&-bass": "drum and bass",
    "dnb": "drum and bass",
    "idm": "idm",
    "ambient-techno": "ambient techno",
    "ambient-dub": "ambient dub",
    "downtempo": "downtempo",
    "chillout": "chillout",
    "noisey": "noise",
    "synthwave": "synthwave",
    "retrowave": "retrowave",
    "future-bass": "future bass",
    "tropical-house": "tropical house",
    "bass-house": "bass house",
    "bass-music": "bass music",
    "bass": "bass music",
    "#electronic": "electronic",
    #
    "#metal": "metal",
    "metal-core": "metalcore",
    "death-core": "deathcore",
    "black-metal": "black metal",
    "blackmetal": "black metal",
    "melodic-black-metal": "melodic black metal",
    "symphonic-black-metal": "symphonic black metal",
    "pagan-black-metal": "pagan black metal",
    "folk-black-metal": "folk black metal",
    "viking-black-metal": "viking black metal",
    "doom-black-metal": "doom black metal",
    "power-metal": "power metal",
    "symphonic-metal": "symphonic metal",
    "doom-metal": "doom metal",
    "sludge-metal": "sludge metal",
    "stoner-rock": "stoner metal",
    "postmetal": "post metal",
    "post-metal": "post metal",
    "progressive-metal": "progressive metal",
    "thrash-metal": "thrash metal",
    "death-metal": "death metal",
    "melodic-death-metal": "melodic death metal",
    "technical-death-metal": "technical death metal",
    "folk-metal": "folk metal",
    "viking-metal": "viking metal",
    "industrial-metal": "industrial metal",
    "groove-metal": "groove metal",
    "blackgaze": "blackgaze",
    "grind-core": "grindcore",
    "grindgaze": "grindcore",
    "cyber-grind": "cybergrind",
    "cybergrind": "cybergrind",
    "war-metal": "war metal",
    "deathgrind": "deathgrind",
    "grind": "grindcore",
    "sludge": "sludge metal",
    "chill-out": "chillout",
    "doom": "doom metal",
    "synthwave-80s": "80s synthwave",
    "2 step": "2step",
    "2-step": "2step",
    "drempop": "dream pop",
    "2000s": "2000s style",
    "bass": "bass music",
    "insrumental": "instrumental",
    "post-metal": "post metal",
    "blackened doom": "blackened doom metal",
    "blackened-death-metal": "blackened death metal",
    "emo-pop": "emo pop",
    "00s": "2000s style",
    "00's": "2000s style",
    "old school death": "old school death metal",
    "prog death": "progressive death metal",
    #
    "avant-garde": "avant garde",
    "avantgarde": "avant garde",
    "musique-concrete": "musique concrete",
    "electroacoustic": "electroacoustic",
    "sound-art": "sound art",
    "experimental-classical": "experimental classical",
    "post-everything": "post everything",
    "algorithmic-music": "algorithmic music",
    "generative": "generative music",
    "hauntology": "hauntology",
    "dubstep-&-electronic": "dubstep",
    "trance.": "trance",
    "shell~wave": "shellwave",
    "classic-90s-house-music-vibes": "90s house",
    #
    "r&b": "rnb",
    "american-oi!": "oi! punk",
    "alt.-folk": "alt folk",
    "3d-sound": "3d soundscapes",
    "60s-music": "60s style",
    "70s-music": "70s style",
    "60s": "60s style",
    "50s": "50s style",
    "70s": "70s style",
    "90s": "90s style",
    "dubstep.": "dubstep",
    "industrial-techno.": "industrial techno",
    "black": "black metal",
    "death": "death metal",
    "r-n-b": "rnb",
    "2000s": "2000s style",
    "jazz-fusion": "jazz fusion",
    "latin-jazz": "latin jazz",
    "jazz-&-hip-hop": "jazz hop",
    "reggaeton-experimental": "reggaeton experimental",
    "trap-latino": "trap latino",
    "new-age": "new age",
    "world-music": "world music",
    "world": "world music",
    "folkrock": "folk rock",
    "folk-rock": "folk rock",
    "alt-country": "alt country",
    "country-rock": "alt country",
    "neo-psych": "neo psych",
    "neopsych": "neo psych",
    "psychedelic-doom-metal": "psychedelic doom metal",
    "celtic": "celtic music",
    "80s,": "80s music",
    "ambient-electronic.": "ambient electronic",
    "techno.": "techno",
    "drum&bass": "drum-and-bass",
    "8bit": "8bit",
    "8-bit": "8bit",
    "hip-hop-(real-shit)": "hip-hop/rap",
    "expiremental": "experimental",
    "rap-&-hip-hop": "hip-hop/rap",
    "rock-n'-roll": "rock and roll",
    "rock-and-roll": "rock and roll",
    "rock'n'roll": "rock and roll",
    #
    "hardcore-punk": "hardcore punk",
    "punk-rock": "punk rock",
    "post-punk-revival": "post punk",
    "punk": "punk rock",
    "emo": "emo",
    "emocore": "emo",
    "mathcore": "mathcore",
    "powerviolence": "powerviolence",
    "cuddlecore": "cuddlecore",
    "psychedelic doom metaal": "psychedelic doom metal",
}


def unify_tag(tag: str) -> str:
    """Normaliza un tag a minúsculas, sin acentos ni espacios, usando TAG_EQUIVALENCES."""
    if not tag:
        return ""

    t = unidecode.unidecode(tag.lower().strip())
    t = t.replace(" ", "-").replace("_", "-")
    t = "-".join(t.split())  # elimina duplicados de espacios

    # Aplica equivalencia si existe
    return TAG_EQUIVALENCES.get(t, t)
